Câu 1:

In [ ]:
import numpy as np

n = 10
a = np.random.randint(1, 15, n)
b = np.arange(0, 200, 2)[:100]
c = np.zeros((n, n))
d = np.eye(n)
e = np.diag(a)

print("Mảng a:")
print(a)
print("Thông số mảng a - ndim: {}, shape: {}, len: {}, itemsize: {}, dtype: {}\n".format(a.ndim, a.shape, len(a), a.itemsize, a.dtype))

print("Mảng b:")
print(b)
print("Thông số mảng b - ndim: {}, shape: {}, len: {}, itemsize: {}, dtype: {}\n".format(b.ndim, b.shape, len(b), b.itemsize, b.dtype))

print("Ma trận c:")
print(c)
print("Thông số ma trận c - ndim: {}, shape: {}, len: {}, itemsize: {}, dtype: {}\n".format(c.ndim, c.shape, len(c), c.itemsize, c.dtype))

print("Ma trận đơn vị d:")
print(d)
print("Thông số ma trận d - ndim: {}, shape: {}, len: {}, itemsize: {}, dtype: {}\n".format(d.ndim, d.shape, len(d), d.itemsize, d.dtype))

print("Ma trận đường chéo e:")
print(e)
print("Thông số ma trận e - ndim: {}, shape: {}, len: {}, itemsize: {}, dtype: {}\n".format(e.ndim, e.shape, len(e), e.itemsize, e.dtype))


Mảng a:
[ 4 12  6  5 10  5  9  7  9 11]
Thông số mảng a - ndim: 1, shape: (10,), len: 10, itemsize: 8, dtype: int64

Mảng b:
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
Thông số mảng b - ndim: 1, shape: (100,), len: 100, itemsize: 8, dtype: int64

Ma trận c:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Thông số ma trận c - ndim: 2, shape: (10, 10), 

Câu 2:

In [3]:
import numpy as np

n = int(input("Nhập kích thước của vector a và b: "))
a = np.array([int(i) for i in input("Nhập mảng a: ").split()])
b = np.array([int(i) for i in input("Nhập mảng b: ").split()])

print("Vector a:")
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Giá trị trung bình:", np.mean(a))
print("Độ lệch chuẩn:", np.std(a))
print("Giá trị trung vị:", np.median(a))

c = np.vstack((a, b)).T
print("\nMa trận c:")
print(c)

mean_b = np.mean(b)
std_b = np.std(b)
d = np.random.normal(mean_b, std_b, (n, n))
print("\nMa trận d (phân phối Gauss):")
print(d)

sum_cd = c + d
diff_cd = c - d
prod_cd = np.matmul(c, d)
inv_d = np.linalg.inv(d)
prod_transpose_inverse = np.matmul(d.T, inv_d)

print("\nTổng của ma trận c và d:")
print(sum_cd)
print("\nHiệu của ma trận c và d:")
print(diff_cd)
print("\nTích của ma trận c và d:")
print(prod_cd)
print("\nTích của ma trận chuyển vị của d và ma trận nghịch đảo của d:")
print(prod_transpose_inverse)

e = np.expand_dims(c, axis=0)
print("\nTensor numpy e:")
print(e)


Nhập kích thước của vector a và b: 2
Nhập mảng a: 1 2
Nhập mảng b: 2 3
Vector a:
Max: 2
Min: 1
Giá trị trung bình: 1.5
Độ lệch chuẩn: 0.5
Giá trị trung vị: 1.5

Ma trận c:
[[1 2]
 [2 3]]

Ma trận d (phân phối Gauss):
[[2.1918329  1.97054863]
 [1.9817559  3.14598778]]

Tổng của ma trận c và d:
[[3.1918329  3.97054863]
 [3.9817559  6.14598778]]

Hiệu của ma trận c và d:
[[-1.1918329   0.02945137]
 [ 0.0182441  -0.14598778]]

Tích của ma trận c và d:
[[ 6.1553447   8.26252418]
 [10.3289335  13.37906058]]

Tích của ma trận chuyển vị của d và ma trận nghịch đảo của d:
[[ 0.99257271  0.00821462]
 [-0.01179064  1.00738529]]

Tensor numpy e:
[[[1 2]
  [2 3]]]


Câu 3:

In [15]:
import numpy as np

diem = np.random.uniform(0, 10, (20, 3))

print("Điểm lớn nhất mỗi môn:", np.max(diem, axis=0))
print("\nĐiểm nhỏ nhất mỗi môn:", np.min(diem, axis=0))

diem = diem.ravel()
print("Mảng sau khi xóa vị trí điểm bằng 0:")
diem = np.delete(diem, np.where(diem == 0))
print(diem)

diem.sort(kind='quicksort')
print("\nMảng sau khi sắp xếp giảm dần:")
print(diem)

k = float(input("Nhập số thực k: "))
insert_index = np.searchsorted(diem, k, side='right')
print("\nVị trí chèn số k mà không phá vỡ tính sắp xếp:", insert_index)

diem = np.insert(diem, insert_index, k)
print("Mảng sau khi thêm số k:")
print(diem)


Điểm lớn nhất mỗi môn: [9.38851954 9.90845797 9.91914372]

Điểm nhỏ nhất mỗi môn: [0.82415631 0.01229771 0.07218976]
Mảng sau khi xóa vị trí điểm bằng 0:
[8.24158714 9.82295979 2.04121573 6.51153984 7.43382719 0.07218976
 2.12877544 5.68232417 7.28926651 4.02317714 9.19382175 8.85425158
 4.89134914 5.52064002 8.71900911 1.33846825 1.56944418 2.3276729
 0.82415631 1.04251134 1.58179555 2.85998852 9.90845797 6.72403437
 8.19402073 3.72758053 6.82054156 6.82726718 6.74511387 4.79648286
 2.87836267 7.65151889 9.91914372 9.38851954 2.66795498 6.24665186
 4.67990554 4.21440113 9.04180798 7.45799457 2.84841385 4.13087357
 5.1552488  0.01229771 2.94950694 3.31052862 1.25619737 2.84158867
 8.82119908 0.78415159 3.78701514 3.95228609 3.68126842 4.98491254
 1.19581051 0.72602378 2.33126477 8.94270764 9.38490364 2.25130664]

Mảng sau khi sắp xếp giảm dần:
[0.01229771 0.07218976 0.72602378 0.78415159 0.82415631 1.04251134
 1.19581051 1.25619737 1.33846825 1.56944418 1.58179555 2.04121573
 2.1287754

In [17]:
import pandas as pd

# Tạo DataFrame mẫu
data = {
    "manufacturer": ["Toyota", "Honda", "Ford"],
    "model": ["Camry", "Civic", "Focus"],
    "Sales_in_thousands": [45, 30, 20],
    "year_resale_value": [12, 10, 15],
    "price_in_thousands": [22, 18, 16],
}

df = pd.DataFrame(data)

# Lưu DataFrame vào file CSV
df.to_csv('car_sale.csv', index=False)


Câu 4:

In [27]:
from google.colab import files

uploaded = files.upload()

Saving Car_sales.zip to Car_sales (3).zip


In [62]:
import pandas as pd
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)
print(df)

so_dong, so_cot = df.shape
print("Số dòng:", so_dong)
print("Số cột:", so_cot)

df['Sales_in_thousands'].fillna(0.0, inplace=True)
df['__year_resale_value'].fillna(df['__year_resale_value'].mean(), inplace=True)
df['Price_in_thousands'].fillna(df['Price_in_thousands'].median(), inplace=True)

vi_tri_thieu_du_lieu = df.isnull().any()
print("\nVị trí thiếu dữ liệu:")
print(vi_tri_thieu_du_lieu)
print("\nDataFrame sau khi điền dữ liệu thiếu:")
print(df)

for cot in df.columns:
    if df[cot].dtype != 'object':
        df = df[df[cot] >= 0]

print("\nDataFrame sau khi xóa hàng vi phạm:")
print(df)

so_dong_trung_lap_truoc_khi_xoa = df.duplicated().sum()
df.drop_duplicates(inplace=True)
so_dong_trung_lap_sau_khi_xoa = df.duplicated().sum()

print("\nSố dòng trùng lặp trước khi xóa:", so_dong_trung_lap_truoc_khi_xoa)
print("DataFrame sau khi xóa các dòng trùng lặp:")
print(df)

df['ID'] = df['Manufacturer'] + '_' + df['Model']
print("\nCột mới 'ID':")
print(df['ID'])

df_ban = df[['ID', 'Sales_in_thousands', '__year_resale_value', 'Price_in_thousands']]
df_xe = df[['ID'] + ['Manufacturer'] + list(df.columns[4:])]

df_ban.to_csv('sale.csv', index=False)
df_xe.to_csv('car.csv', index=False)


    Manufacturer    Model  Sales_in_thousands  __year_resale_value  \
0          Acura  Integra              16.919               16.360   
1          Acura       TL              39.384               19.875   
2          Acura       CL              14.114               18.225   
3          Acura       RL               8.588               29.725   
4           Audi       A4              20.397               22.255   
..           ...      ...                 ...                  ...   
152        Volvo      V40               3.545                  NaN   
153        Volvo      S70              15.245                  NaN   
154        Volvo      V70              17.531                  NaN   
155        Volvo      C70               3.493                  NaN   
156        Volvo      S80              18.969                  NaN   

    Vehicle_type  Price_in_thousands  Engine_size  Horsepower  Wheelbase  \
0      Passenger               21.50          1.8       140.0      101.2   
1      

Câu 5:

In [64]:
import pandas as pd

df = pd.read_csv("sale.csv")
df1 = pd.read_csv("car.csv")

tong_sl_xe_ban = df["Sales_in_thousands"].sum()
print(f"Tổng số lượng xe bán được: {tong_sl_xe_ban}")

gia_tb_o_to = df["Price_in_thousands"].mean()
print(f"Giá trung bình của ô tô: {gia_tb_o_to}")

top_10_xe_max_price = df.nlargest(10, "__year_resale_value")
print(top_10_xe_max_price.head(10))

quantity = df1.groupby("Vehicle_type")["Vehicle_type"].count()
print(f"Quantity of Vehicle: {quantity}")

mode = df1["Manufacturer"].mode()
print(f"Hãng xe có số lượng xuất hiện nhiều nhất (mode): {mode[0]}")

df_sort_giam_dan = df.sort_values(by=["Sales_in_thousands", "__year_resale_value", "Price_in_thousands"], ascending=False)
print(f"Sau khi sắp xếp:\n{df_sort_giam_dan}")

df_gop = pd.merge(df, df1, on="ID")
print(f"Sau khi gộp:\n{df_gop.head()}")


Tổng số lượng xe bán được: 8110.579000000001
Giá trung bình của ô tô: 27.33182236842105
                         ID  Sales_in_thousands  __year_resale_value  \
121  Porsche_Carrera Cabrio               1.866               67.550   
120   Porsche_Carrera Coupe               1.280               60.625   
91      Mercedes-B_SL-Class               3.311               58.600   
35              Dodge_Viper               0.916               58.470   
90       Mercedes-B_S-Class              16.774               50.375   
89       Mercedes-B_E-Class              27.602               41.450   
119          Porsche_Boxter               8.982               41.250   
69              Lexus_LS400               6.375               40.375   
5                   Audi_A8               1.380               39.000   
22       Chevrolet_Corvette              17.947               36.225   

     Price_in_thousands  
121              74.970  
120              71.020  
91               82.600  
35             

Câu 6:

In [69]:
import numpy as np
import pandas as pd

np.random.seed(42)
du_lieu_mang = np.random.randint(range(18, 23), size=(50, 1), dtype=int)
du_lieu_mang = np.hstack((du_lieu_mang, np.random.choice(["CNTT", "KTPM", "KHMT", "HTTT", "CNDPT"], size=(50, 1))))
du_lieu_mang = np.hstack((du_lieu_mang, np.random.choice([np.nan, "Novice", "Intermediate", "Advanced"], size=(50, 1))))
du_lieu_mang = np.hstack((du_lieu_mang, np.random.choice(range(11), size=(50, 1))))
du_lieu_mang = np.hstack((du_lieu_mang, np.random.choice(range(11), size=(50, 1))))
du_lieu_mang = np.hstack((du_lieu_mang, np.random.choice(range(11), size=(50, 1))))
du_lieu_mang = np.hstack((du_lieu_mang, np.random.choice(range(11), size=(50, 1))))

cot = ["Tuổi", "Ngành", "Typing", "Lập trình thi đấu", "Web", "AI-Tank", "Rung chuông vàng"]
df = pd.DataFrame(du_lieu_mang, columns=cot)

df["ID"] = range(1, 51)
df["Tổng cuộc thi"] = df.iloc[:, 3:7].count(axis=1)
df["Tổng điểm"] = df.iloc[:, 3:7].sum(axis=1)

print(df)

top_3_diem_cao_nhat = df.nlargest(3, "Tổng điểm")[["ID", "Tuổi", "Ngành"]]
print("\nTop 3 người có tổng điểm cao nhất:")
print(top_3_diem_cao_nhat)

xu_huong_tham_gia_CNTT = df[df["Ngành"] == "CNTT"].iloc[:, 3:7].mean().idxmax()
print(f"\nNgành CNTT có xu hướng tham gia cuộc thi: {xu_huong_tham_gia_CNTT}")

cuoc_thi_nhieu_nguoi_tham_gia_nhat = df.iloc[:, 3:7].count().idxmax()
print(f"\nCuộc thi có số lượng tham gia lớn nhất là: {cuoc_thi_nhieu_nguoi_tham_gia_nhat}")

cuoc_thi_it_nguoi_tham_gia_nhat = df.iloc[:, 3:7].count().idxmin()
print(f"\nCuộc thi có số lượng tham gia ít nhất là: {cuoc_thi_it_nguoi_tham_gia_nhat}")


   Tuổi  Ngành        Typing Lập trình thi đấu Web AI-Tank Rung chuông vàng  \
0     6   CNTT      Advanced                 3   0       7                0   
1    14   HTTT  Intermediate                 6  10       0                3   
2    10   KTPM  Intermediate                10   0      10                0   
3     7   HTTT        Novice                 2   1       8                4   
4    20   KTPM      Advanced                 5   1       8                3   
5     6   KTPM           nan                 1   5       1                7   
6    18   HTTT  Intermediate                 9   6       6                7   
7    10  CNDPT      Advanced                 8   4       9                6   
8    10   KTPM      Advanced                 4   0       2                2   
9    20   KTPM        Novice                 5   0       6                0   
10    3   HTTT  Intermediate                 3   2       9                0   
11    7   KTPM  Intermediate                10   1  